Module MapModule

    '''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    ' CICS Client Visual Basic constant file for xxmap2.bms
    '
    ' Generated by CICS BMS Conversion Utility - Version 1.0
    ' This file can be loaded into a code module

    ' MAP1Map constants
    Public Const MAP1 = "0.52.80.114.160.194.350.365.373.506.517.520.529.531.597.600.609.611.677.680.689.691.757.760.769.771.837.840.849.851.983.1000.1022.1148.1160.1182.1240.1262.1320.1342.1400.1404.1408.1552.1562.1566.1568.1572.1574.1579.1694.1849.1870.1888"
    Public Const MAP1_HEAD = 114
    Public Const MAP1_HEAD2 = 194
    Public Const MAP1_STUNUM = 365
    Public Const MAP1_CRS1 = 520
    Public Const MAP1_DESC1 = 531
    Public Const MAP1_CRS2 = 600
    Public Const MAP1_DESC2 = 611
    Public Const MAP1_CRS3 = 680
    Public Const MAP1_DESC3 = 691
    Public Const MAP1_CRS4 = 760
    Public Const MAP1_DESC4 = 771
    Public Const MAP1_CRS5 = 840
    Public Const MAP1_DESC5 = 851
    Public Const MAP1_SNAME = 1000
    Public Const MAP1_ADDR1 = 1160
    Public Const MAP1_ADDR2 = 1240
    Public Const MAP1_ADDR3 = 1320
    Public Const MAP1_POSTC1 = 1400
    Public Const MAP1_POSTC2 = 1404
    Public Const MAP1_PHONE1 = 1562
    Public Const MAP1_PHONE2 = 1568
    Public Const MAP1_PHONE3 = 1574
    Public Const MAP1_MESSAGE = 1694
    Public Const MAP1_MENUKEY = 1849
    Public Const MAP1_DELCMNT = 1888

End Module
